# SPDX-FileCopyrightText: 2024 Frans van Dorsselaer
#
# SPDX-License-Identifier: MIT

---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: 'Save runtime cache'

description: 'Save the given runtime cache (which must exist as Xmss/runtimes/**)'

inputs:
  runtime:
    description: 'Runtime identifier'
    required: true

runs:
  using: composite

  steps:
    - id: lookup-runtime-cache
      uses: ./.github/actions/lookup-runtime-cache
      with:
        runtime: ${{ inputs.runtime }}

    - id: delete
      if: ${{ steps.lookup-runtime-cache.outputs.cache-hit }}
      uses: actions/github-script@v7
      env:
        RUNTIME_CACHE_KEY: ${{ steps.lookup-runtime-cache.outputs.key }}
      with:
        script: |
          const { RUNTIME_CACHE_KEY } = process.env
          const runtime_caches = await github.rest.actions.getActionsCacheList({
            owner: context.repo.owner,
            repo: context.repo.repo,
            key: `${RUNTIME_CACHE_KEY}`,
          })
          for (const runtime_cache of runtime_caches.data.actions_caches) {
            github.rest.actions.deleteActionsCacheById({
              owner: context.repo.owner,
              repo: context.repo.repo,
              cache_id: runtime_cache.id,
            })
          }

    - id: save
      uses: actions/cache/save@v4
      with:
        path: |
          Xmss/runtimes/**
        key: ${{ steps.lookup-runtime-cache.outputs.key }}
        enableCrossOsArchive: true
