// SPDX-FileCopyrightText: 2024 Frans van Dorsselaer
//
// SPDX-License-Identifier: MIT

namespace Dorssel.Security.Cryptography;

/// <summary>
/// Indicates which part of an XMSS key is being processed by <see cref="IXmssStateManager"/>.
/// </summary>
public enum XmssKeyPart
{
    /// <summary>
    /// The stateless private part of an XMSS key, which is generated by <see cref="Xmss.GeneratePrivateKey"/>.
    /// </summary>
    /// <remarks>
    /// This part must be protected for both confidentiality and integrity.
    /// </remarks>
    PrivateStateless,
    /// <summary>
    /// The stateful private part of an XMSS key, which is generated by <see cref="Xmss.GeneratePrivateKey"/>.
    /// </summary>
    /// <remarks>
    /// This part must be protected for both confidentiality and integrity.
    /// <para>This part is updated every time signatures are created.</para>
    /// </remarks>
    PrivateStateful,
    /// <summary>
    /// The public part of an XMSS key, which is generated by <see cref="Xmss.CalculatePublicKeyAsync"/>.
    /// </summary>
    /// <remarks>
    /// This part does not have to be protected; it does not contain confidential information and can be regenerated if it gets corrupted.
    /// </remarks>
    Public,
}
