# SPDX-FileCopyrightText: 2024 Frans van Dorsselaer
#
# SPDX-License-Identifier: MIT

---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# Because parameterized reusable workflow names are not supported, we need this "switch board".

name: Build runtime

on:
  workflow_dispatch:
    inputs:
      runtime:
        description: 'A runtime identifier (RID)'
        required: true
        type: string

  workflow_call:
    inputs:
      runtime:
        description: 'A runtime identifier (RID)'
        required: true
        type: string

permissions:
  contents: read
  actions: write

jobs:
  build-linux-x64:
    uses: ./.github/workflows/runtime-linux-x64.yml
    if: inputs.runtime == 'linux-x64'

  build-win-x64:
    uses: ./.github/workflows/runtime-win-x64.yml
    if: inputs.runtime == 'win-x64'

  build-browser-wasm:
    uses: ./.github/workflows/runtime-browser-wasm.yml
    if: inputs.runtime == 'browser-wasm'
