# SPDX-FileCopyrightText: 2024 Frans van Dorsselaer
#
# SPDX-License-Identifier: MIT

# This file requires LF line endings, as it is used in GitHub action hashes.

---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# This file requires LF line endings, as it is used in cross-platform GitHub action hashes.

name: Runtime browser-wasm

on:
  workflow_dispatch:
  workflow_call:

env:
  RUNTIME: browser-wasm

permissions:
  contents: read
  actions: write

jobs:
  build-browser-wasm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Calculate cache key
        id: cache-key
        run: |
          echo "value=runtime-${{ env.RUNTIME }}-${{ hashFiles('.gitmodules', 'libc/libc.c', '.github/workflows/runtime-browser-wasm.yml') }}" \
            >> "$GITHUB_OUTPUT"

      - name: Prepare packages
        run: |
          sudo apt-get update
          sudo apt-get install -y emscripten

      - name: Configure
        run: >
          emcmake cmake
          -S xmss-library
          -B build
          -DXMSS_C99_COMPATIBLE=OFF
          -DXMSS_BUILD_TESTS=OFF

      - name: Build
        run: cmake --build build

      - name: Copy artifact
        run: |
          mkdir -p "Xmss/runtimes/${{ env.RUNTIME }}/nativeassets"
          cp build/src/libxmss.a "Xmss/runtimes/${{ env.RUNTIME }}/nativeassets/xmss.a"

      - name: Check existing cache
        id: cache-check
        uses: actions/cache/restore@v4
        with:
          path: |
            Xmss/runtimes/**
          key: ${{ steps.cache-key.outputs.value }}
          enableCrossOsArchive: true
          lookup-only: true

      - name: Delete existing cache
        if: ${{ steps.cache-check.outputs.cache-hit }}
        run: |
          gh extension install actions/gh-actions-cache
          gh actions-cache delete "${{ steps.cache-key.outputs.value }}" --confirm
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save cache
        uses: actions/cache/save@v4
        with:
          path: |
            Xmss/runtimes/**
          key: ${{ steps.cache-key.outputs.value }}
          enableCrossOsArchive: true
