# SPDX-FileCopyrightText: 2024 Frans van Dorsselaer
#
# SPDX-License-Identifier: MIT

---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# This file requires LF line endings, as it is used in cross-platform GitHub action hashes.

name: Runtime browser-wasm

on:
  workflow_dispatch:
  workflow_call:

env:
  RUNTIME: browser-wasm

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Prepare packages
        run: |
          sudo apt-get update
          sudo apt-get install -y emscripten

      - name: Configure
        run: >
          emcmake cmake
          -S xmss-library
          -B build
          -DXMSS_C99_COMPATIBLE=OFF
          -DXMSS_BUILD_TESTS=OFF

      - name: Build
        run: cmake --build build

      - name: Copy artifact
        run: |
          mkdir -p "Xmss/runtimes/${{ env.RUNTIME }}/nativeassets"
          cp build/src/libxmss.a "Xmss/runtimes/${{ env.RUNTIME }}/nativeassets/xmss.a"

      - name: Save runtime cache
        id: save-runtime-cache
        uses: ./.github/actions/save-runtime-cache
        with:
          runtime: ${{ env.RUNTIME }}
