# SPDX-FileCopyrightText: 2024 Frans van Dorsselaer
#
# SPDX-License-Identifier: MIT

---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# This file requires LF line endings, as it is used in cross-platform GitHub action hashes.

name: Runtime linux-x64

on:
  workflow_dispatch:
  workflow_call:

env:
  RUNTIME: linux-x64

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Configure
        run: >
          cmake
          -S xmss-library
          -B build
          -DBUILD_SHARED_LIBS=ON
          -DXMSS_C99_COMPATIBLE=OFF
          -DXMSS_SHAKE256_256=OverrideInternal
          -DXMSS_HASH_OVERRIDE_SOURCES="../../libc/libc.c"
          -DCMAKE_C_COMPILER=clang
          -DCMAKE_SHARED_LINKER_FLAGS="-nostdlib -s"

      - name: Build
        run: cmake --build build

      - name: Test
        working-directory: build
        run: ctest

      - name: Copy artifact
        run: |
          mkdir -p "Xmss/runtimes/${{ env.RUNTIME }}/native"
          cp build/src/libxmss.so "Xmss/runtimes/${{ env.RUNTIME }}/native/xmss.so"

      - name: Save runtime cache
        id: save-runtime-cache
        uses: ./.github/actions/save-runtime-cache
        with:
          runtime: ${{ env.RUNTIME }}
