# SPDX-FileCopyrightText: 2024 Frans van Dorsselaer
#
# SPDX-License-Identifier: MIT

# This file requires LF line endings, as it is used in GitHub action hashes.

---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# This file requires LF line endings, as it is used in cross-platform GitHub action hashes.

name: Runtime linux-x64

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  actions: write

jobs:
  build-linux-x64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure
        run: >
          cmake
          -S xmss-library
          -B build
          -DCMAKE_C_COMPILER=clang
          -DXMSS_C99_COMPATIBLE=OFF
          -DBUILD_SHARED_LIBS=ON

      - name: Build
        run: cmake --build build

      - name: Test
        working-directory: build
        run: ctest

      - name: Copy artifact
        run: |
          mkdir -p Xmss/runtimes/linux-x64/native
          cp build/src/libxmss.so Xmss/runtimes/linux-x64/native/xmss.so

      - name: Check existing cache
        id: cache-check
        uses: actions/cache/restore@v4
        with:
          path: |
            Xmss/runtimes/**
          key: runtime-${{ inputs.runtime }}-${{ hashFiles('.gitmodules', '.github/workflows/runtime-linux-x64.yml') }}
          enableCrossOsArchive: true
          lookup-only: true

      - name: Delete existing cache
        if: ${{ steps.cache-check.outputs.cache-hit }}
        run: |
          gh extension install actions/gh-actions-cache
          gh actions-cache delete "runtime-${{ inputs.runtime }}-${{ hashFiles('.gitmodules', '.github/workflows/runtime-linux-x64.yml') }}" --confirm
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save cache
        uses: actions/cache/save@v4
        with:
          path: |
            Xmss/runtimes/**
          key: runtime-linux-x64-${{ hashFiles('.gitmodules', '.github/workflows/runtime-linux-x64.yml') }}
          enableCrossOsArchive: true
